title: OWASP Halifax
author: Lilly Chalupowski
email: lilly.chalupowski@owasp.org
description: OWASP Halifax Website
github_username: lillypad
plugins:
  - jekyll-tidy
include:
  - _pages
  - _slides
exclude:
  - Makefile
  - LICENSE
  - watch.sh
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - README.md
  - node_modules
markdown: kramdown
strict_front_matter: true
